{% set version = "0.4.1" %}

{% set posix = 'm2-' if win else '' %}

package:
  name: r-downloader
  version: {{ version|replace("-", "_") }}

source:
  fn: downloader_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/downloader_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/downloader/downloader_{{ version }}.tar.gz
  sha256: 74595ff67e9600e3bbe25fa2daf2eec770fab9eaaea12e63b61a32086e035175

build:
  noarch: generic
  number: 0

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]

  host:
    - r-base
    - r-digest

  run:
    - r-base
    - r-digest

test:
  commands:
    - $R -e "library('downloader')"           # [not win]
    - "\"%R%\" -e \"library('downloader')\""  # [win]

about:
  home: https://github.com/wch/downloader
  license: GPL-2
  summary: Provides a wrapper for the download.file function, making it possible to download files over HTTPS on Windows, Mac OS X, and other Unix-like platforms. The 'RCurl' package provides this functionality (and much more) but can be difficult to install because it must be compiled with external dependencies. This package
    has no external dependencies, so it is much easier to install.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
