appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: KxssKYWx/uCBHHvcrozi9ktxiqjv+ZO0Cz0vGv2EtfOm5+hn5u1B1kGQ/nHnh/4PTO/+dCI5kvhy3ELbGrPU4iEYUSvxmGSXEUTUP84SUrspP5efpASE4RRz6O5IO40DwDgALCwUObacaVh2clG4PLSbQKNwkQsBLpjZzrVVoCZ5vBAUPf5rYf/kq7t9MJVNzM9hOU2rc8/eEeQKEFHmgMrrh3xVwLAVt393Xdfu+/ifAMt8Ltr/Al1kqsE0gnv+Qu5aSEo4q6WwQeM2tMqZ8Qs8+LlQFBbD4ubw4wsaEV/mGPg9i+hX8JbgVvtqTLTI73UQ72wb3MQmdMT4BPr/2AhmrgEEDc9HnIHTbjn3VZJoB+cXY2gCr5WE03l0LA4t89b/YQklGHOj3krUJbPSJTwNkRbEiWAFQ8PmhkqtnATXJNTlGS7pk/Z5bqCMMs4lDtMkQ/wgUFuqw0mn2cCV+iSV+chaNFXUBnjs9s3VAOwV+QqOn+/B648sgWNPbsmEd2PjNNi6jcRtdv6siPvLcabqpCpWRYRISBc5GRF2yb+7kRm2JHeYQGd9mM9w+Sc/jIYRGvyBhLZwFCkm3bxUV7kKOhRB8EO0Brl1Y9NHDg48M3uwt0madxxJDO0ZFRmDIx31cGk2uj2MNoFJDt/a6WiFI98PtdMWUeFX2WIle9g=}
