travis:
  secure:
    BINSTAR_TOKEN: TqfuaP/IF9YkIgZCGhMHa50AjgS+c5dhxZbQPq+/mxaKMg6xf/tUkZpV2kpvF51Fgy1i3YolSv6nv45umrAoULptT0c8j39pTnwGgRddJTyfC/hV4Tk0r6StMTYnwrv0OkDNB6HCrVP4NC/sguGSjib6SpWhVpRYckuXitnBjbUeCMWy7x5axNH2DafIvGBhDFZAUbSN40ZHwkZ+vHWA+cHlZO8OmA3pOQRSiBZ9kjBCYtgNf94sDlTEJM3kPeOtqaiKlGt4YDjOP+OoKoX+KJBSJ+kvOqnLJq3iH25q86V9WZLtBVaqPdSBW7EFj/MUqohNYdkVvYu9ga/cjicMX3h+Fc8q+CkjFuAomdztO0l9rysIjVg0wB5lomNOBTFhX8EW/VZgpB9QUyEsPAuRLgAajFKqX5Q3Xi0rkDd3CzJf3rt26RvkC7wL3AdaO/9uloewj1ZtA7S8sxAVJV0YXeX+nVCubKFEZ6gqQLne3LAC+FymRCjK9/FB8NdAIzT9TVg7x1bYywNWnizn+DF+1p2NTgBfCRp43whQuAkHQBQdryC+p8njAUZs+piXvFT5l/SCTru/WydpgvRyW056xB8pKwHHlIq3N30GWvwGVxHGmbFhxo+xOQsJcZ16P/l7zIQ+bvHWDSGahh2fCwSjumK0RdPJl5DD82V+lxYgEGw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
